_posts/2015-10-27-do-it-chrome-extension.md
=> Updated post "Do it!"

_posts/2015-09-12-emotions-through-css.md, _posts/2015-10-07-music-emojis.md, _posts/2015-10-08-briiian.md, _posts/2015-10-13-glitch.md, _posts/2015-10-22-humans-dot-text.md, _posts/2015-10-23-elastic-loading-bars.md, _posts/2015-10-24-poop-fiction.md, _posts/2015-10-26-swiss-style-color-picker.md
=> Updated all posts before "Do it!"

_posts/2015-09-11-meet-inspiring-online.md
=> Updated post in "About"

_config.yml, _includes/pagination.html, css/stylesheet.scss
This PR:
* Updates `paginate_path` on `config.yml`.
* Removes unnecessary `disabled` spans.
* Adds styles for paginator buttons.
Here's a screenshot of how it's looking:
I focused on fixing the pagination, let's think about the "we can play around a little as well" part.
Closes #39
=> Fix pagination

_posts/2015-10-08-briiian.md, _posts/2015-10-27-do-it-chrome-extension.md, _posts/2015-10-29-uberviz.md
Changed some small things in the posts "Briiian", "Do it!" and "Music
visualizers for the web"
=> Minor changes

_posts/2015-10-30-kitty-keys.md, _posts/2015-11-02-pt-code-experiments.md
Fixed some typos in "Kitty Keys" and "PT Code Experiments"
=> Fixed some typos

_posts/2015-10-29-uberviz.md
Fixed a broken link in "Music visualizers for the web" which should
normally work
=> Fixed broken link

_layouts/post.html, _posts/2015-11-11-why-skeuomorphism-is-like-a-classic-car.md, index.html
Feel free to change or improve my wording. ‘Vimeo’ variable is kinda shitty(maybe for now) I think we should have two variables: ‘vimeo-id’ and ‘youtube-id’
Cheers
=> Add Why Skeuomorphism Is Like a Classic Car(fixes #53)

_data/contributors.yml, contributors/index.html, css/stylesheet.scss
This cleans up the template a little bit and makes it easier to manage contributors.
=> Move contributors into data file

contributors/index.html
This snuck in, in the last commit.. sorry.
=> Remove contributions reference in the template

_data/contributors.yml, contributors/index.html
Fixed page "Contributors" + added Vaidas Lamanauskas and Johannes Jakob as contributors
=> Fixed page "Contributors" + added contributors

_posts/2015-09-11-meet-inspiring-online.md
Fix tiny typo, add (presumed) missing word and fix contributing link
=> Small fixes

contributors/index.html
* Mention where the info is located
* don't use info:, that info isn't used anywhere, so a comment would be better
=> change the contributors' note

_posts/2016-02-12-passweird.md
Small mistake, [here](https://github.com/tholman/inspiring-online/commit/11ad36d9122b74c1819fc2975a0483abb36bf8aa)'s the file now.
=> Rename *passweird to *passweird.md

css/stylesheet.scss
This helps with issue #115. This makes the pagination buttons be pushed in from the sides a little bit.
=> Add margins to the paginate buttons

_posts/2016-3-3-jetlag.md
=> adds jetlag.photo

_posts/2016-03-03-jetlag.md
todo: add image, write second line
cc @TJScalzo @JohJakob
=> fix the errors @TJScalzo outlined

_posts/2016-3-3-jetlag.md
Reverts tholman/inspiring-online#129
=> Revert "fix the errors @TJScalzo outlined"

_layouts/base.html, _layouts/post.html, _posts/2015-10-13-glitch.md, _posts/2015-10-23-elastic-loading-bars.md, _posts/2015-10-28-3d-parallax-icons.md, _posts/2015-10-29-uberviz.md, _posts/2015-11-02-pt-code-experiments.md, _posts/2015-11-05-type-hunting.md, _posts/2015-11-10-hiphop-quoted.md, _posts/2015-11-11-why-skeuomorphism-is-like-a-classic-car.md, _posts/2015-11-12-animated-book-covers.md, _posts/2015-11-13-css-gram.md, _posts/2015-11-16-matt-deslauriers-javascript-sketches.md, _posts/2015-11-17-typesource.md, _posts/2015-11-19-image-grid-effects.md, _posts/2016-01-29-ghostly-snowden.md, _posts/2016-02-10-mojs.md, _posts/2016-03-01-patatap.md, _posts/2016-03-03-jetlag.md, index.html
I tried to change them to a type that better matches what they're about. I added these types:
- Talk
- Resource
- Coding
- CodePen
- Typography
- CSS Madness
- Beautiful
(Helps with #133)
=> New types applied to posts

css/stylesheet.scss
These are the same as used in the 404 page
=> add fallback fonts for brandon-grotesque

_layouts/post.html, css/stylesheet.scss, index.html
I turned the if statements into elsif statements that are all joined together. This prevents, for example, both an image and a YouTube video appearing at the same time.
I also altered the CSS slightly so that iframes have gre/ay borders like the images do.
=> Improved the images/iframes of posts

_posts/2016-03-07-playthings.md
Just some minor grammar and punctuation fixes.
=> Minor grammar fixes

css/stylesheet.scss
Not perfect. Will do for now :)
=> Responsive nav

_layouts/post.html, css/stylesheet.scss, index.html
This is something that I figured out for using on a different site. When I went to check the responsive nav I noticed the same problem we faced on their; black bars around the videos. So I went ahead and made the changes.
=> Makes iframe videos keep their ratio when scaled down

_posts/2016-03-07-paper-letter-typography.md, _posts/2016-03-07-playthings.md
This is related to #30
If this is added for every post, it can't happen again
=> Adds a precise day to the double posts on one day

_posts/2016-03-09-pixel.md
=> fix naming of recent post: pixels --> pixel

_posts/2016-03-09-pixel.md
- authorUrl
- url->link
- pixel->Pixel
- Phrasing
Helps #153
=> Fixed several issues in Pixel post

_posts/2016-03-09-pixel.md
I reverted "works on mobile" back to "works perfectly in your palm" but with punctuation.
=> Undid changing of phrasing in pixel post

_posts/2016-03-20-paper-peninsula.md, _posts/2016-03-21-somerset.md, _posts/2016-03-22-waves.md
I added a missing apostrophe and removed some slashes at the end of links. Like I say in the commit message I'm not sure if it's required but I've seen other people remove them.
=> Minor grammar fix and link fixes

_posts/2016-04-18-greatness.md
Hi there,
This is just a tiny change to remove the possessive apostrophe.
Big fan of your site.
All the best,
Michael :)
=> Tiny typo fix

_posts/2016-04-11-nosaj-thing.md, _posts/2016-04-17-plane-site.md, _posts/2016-04-18-greatness.md
Yes, I know it doesn't really do anything. I just thought I'd do this. Also, the point could be made that those tiny bytes that are removed when the slashes are deleted could slow the site's loading time. I know that amount of time is so small that it isn't even noticeable, but why not y'know? It's not like it's a bad thing, right?
=> Removed slashes from ends of urls

404.html, README.md, _config.yml, _includes/menu.html, _includes/pagination.html, _includes/posts-loop.html, _layouts/base.html, _layouts/post.html, categories/index.html
Also added a link to the wiki in the README. 
(Fixes #193)
=> Added functionality for showing changes on forks

_layouts/post.html, _posts/2016-04-01-the-corndog-party.md, _posts/2016-04-26-eschersketch.md, _posts/2016-05-12-ducks-are-the-best.md, _posts/2016-05-13-tick-tock.md, _posts/2016-05-16-leila-mcglew.md
Add ?ref=inspiring.online for reference (fixes #160)
remove trailing slashes
=> Add ?ref=inspiring.online

random/index.html
I wanted to see if I could do this and I eventually figured it out.
I'm not sure if this should be added to the menu since it's getting a little crowded. I was thinking it could just exist as an easter egg for those who find it.
**BTW:**
I posted this as a PR because I want feedback and responses. I could've just added this directly to the site, but I want some discussion and ideas contributed before it's added.
=> Add random page

feed.xml
Checks if .remoteImage
fixes #219
=> remote image in feed

js/inspiring-online.js
(I've been working on a way to do this since the redesign; I'm really glad I figured it out.)
Let me know what you guys think! The reasoning behind doing this makes sense, right?
=> Made posts not show up in grid when on their page

_layouts/post.html
This layout should be compressed too
see #237 #102
=> compress the post page

_posts/2016-03-07-paper-letter-typography.md
=> fix papercraft url

README.md
Front Matter attribute `isGone` is now `siteDown`. Changed wording in [README.md](https://github.com/tholman/inspiring-online#contributing) to reflect this.
=> Changed wording in README.md to reflect changed attribute name

_posts/2017-05-12-learning-music.md
=> Capitalised first letter of blurb

_posts/2017-05-12-learning-music.md
Sorry, probably would of been better to of put all these on 1 PR
=> Added website to footer

_posts/2017-07-20-from-another-room.md
[From Another Room](http://fromanotherroom.tumblr.com/) is down.
=> Update From Another Room

_posts/2017-10-06-couch-2048.md
=> Trailing slash makes this URL invalid and page does not load

_posts/2018-05-01-pure-css-francine.md
=> Fix spelling error

_posts/2016-02-19-emoji-party.md
=> Indicate Emoji Party as down

_posts/2017-09-27-winamp2-js.md
=> Rename Winamp2-js to Webamp

content/posts/2020-01-10-please-touch-the-artwork.md
I noticed that the new posts for this site are being made in a more long-form, conversational style. I also saw that you're accepting PRs that fix errors in posts. I enjoy editing peoples' writing so I thought I'd suggest some fixes. Please let me know if any of these changes are too formal or go against the style of writing you're trying to evoke.
=> Fixes for Please, Touch the Artwork

content/posts/2020-01-23-musical-experiments.md
=> musical experiments

content/posts/2020-01-15-gt-alpina.md, content/posts/2020-01-15-guess-my-word.md, content/posts/2020-01-17-computational-knitwear.md, content/posts/2020-01-17-portfolio-day.md, content/posts/2020-01-18-sandspiel.md, content/posts/2020-01-20-lars-experiments.md, content/posts/2020-01-23-marvin-visions.md, content/posts/2020-01-23-musical-experiments.md
Just as the title of the issue says, this is a pull request with fixes for the most recent posts. Essentially all of the changes were minor.
=> General fixes for new batch of posts

content/posts/2020-01-25-fifty-two-days-of-canvas-creativity.md
These are just some minor fixes. I also added a link to Luke Patton's website at the end.
=> General fixes for 52 Weeks of Canvas

content/posts/2020-01-28-cineshader.md, content/posts/2020-01-29-plottertwitter-of-the-month-january.md
The main things I changed were the use of past perfect tense and some capitalization. I also made sure to mention Lusion earlier in the CineShader post so that it's clear why there's a link to them at the bottom.
=> General fixes for PlotterTwitter and CineShader

content/posts/2020-02-02-manifest-app.md
These are just some basic phrasing changes to aid in clarity. I also added a link to Jonathon's site at the bottom to match the links in previous posts.
=> General fixes for Manifest App

content/posts/2020-02-04-butts.md
These are just some very minor fixes.
@tholman Is there are reason the link to Buttsss.com at the end of the post is spelled out as "Buttsss dot com"? I wasn't sure if you had done it for a specific reason so I didn't change it. If not, I would suggest just writing it as it appears elsewhere in the post.
=> General fixes for Buttsss

content/posts/2020-02-13-leg-breaker.md, content/posts/2020-02-13-pokemon-master.md, content/posts/2020-02-15-eight-bit-code.md, content/posts/2020-02-15-what-color-is-your-name.md
Nearly all of the changes were very minor. In the Pokémon post I included the accent and capitalized things consistently. In the Leg Breaker post I added a link to the creator's Twitter at the bottom of the post since the Tweet embedded in the post wasn't their's.
=> General fixes for four recent posts

content/posts/2020-02-15-eight-bit-code.md
I reverted some of my changes when merging e6520fc and forgot to add them back in. I didn't end up proofreading the updated post until just now!
=> More general fixes for 8 Bit Code

content/posts/2020-02-21-generative-placeholders.md, content/posts/2020-02-21-textreme.md
Some very minor fixes, mainly phrasing and clarity changes.
=> General fixes for TEXTREME & Generative Placeholders

content/posts/2020-01-17-computational-knitwear.md, content/posts/2020-02-23-tinkersynth.md
These are mostly phrasing changes. 
**Note:** The code is public on GitHub, but not open-source in the traditional sense. The creator still retains the copyright and he's not open to contributions. (Does this kind clarification require another sentence, or is changing "open-source" to "public" enough?)
=> General fixes for Tinkersynth & tiny fix for Computational Knitwear

content/posts/2020-02-26-plink-plonk.md
Just some phrasing fixes to improve clarity
=> General fixes for Plink Plonk

content/posts/2020-01-29-plottertwitter-of-the-month-january.md, content/posts/2020-02-15-eight-bit-code.md, content/posts/2020-02-29-generated-space.md, content/posts/2020-03-01-best-of-plottertwitter-february.md, content/posts/2020-03-02-broider.md
These are all very simple changes to the posts.
The only thing I'm not sure about is 3e3a1fc1fc71607ef173f65ac15816b5b28509d6 where I changed the links to be references instead of hardcoded to the site's URL. Let me know if there's any particular reason Hugo's `ref` shortcode and relative links shouldn't be used.
=> General fixes for newest posts & relative link updates

static/css/styles.css, static/js/index.js
This is exactly what the title says! I moved the styling of category titles out of the JS and into CSS. I also created variables for each color in case there's a need or want to use them in other places.
(Fixes #348)
=> Move category title styling to CSS

content/posts/2020-03-05-intimacy.md
I just switched out some words to improve clarity. I also added some links to the end.
=> General fixes for Intimacy

content/posts/2020-03-08-viewfinder.md
I fixed up the clarity of some sentences by restructuring them slightly. I switched out some word choices to give them more specific meaning. I also added links to Matt's website.
=> General fixes for Viewfinder

content/posts/2020-03-09-wash-those-hands.md
These are just a couple minor changes.
=> General fixes for Wash Those Hands

content/posts/2020-06-08-kung-fu-chess.md
A very quick fix to a slight error in the title of Kung Fu Chess
=> Fix spelling error in Kung Fu Chess title
